### ISSUE TITLE
Navbar menu links have margin between text and underline

### ISSUE THREAD

**Issue by Nightfirecat** [kaiiiz/hugo-theme-monochrome#15]
Refer to screenshot of `li.navbar-item.pure-menu-item`: (containing `a.pure-menu-link`)
![](https://user-images.githubusercontent.com/2199511/163297389-156b9727-1409-4e8e-b523-ef2f3eefd065.png)

When I encountered this theme, I was surprised that it was possible to hover the list item and cause the bottom border to appear without being able to click on the link contained within it. I would expect the vertical space between them to be clickable. (including the border, ideally) On other sites, I see this achieved by applying little-to-no styling on the list items, instead opting to style the `<a>`s contained within to ensure all padding and borders are clickable.

**Comment by kaiiiz** [comment]
Thank for pointing out the issue. You're right. Adding style to `<a>` should be better than adding it to the list item. I'll fix it and it'll be available in the next release.

**Comment by kaiiiz** [comment]
Fixed in v2.0.0.
