### ISSUE TITLE
Heading links

### ISSUE THREAD

**Issue by Nightfirecat** [kaiiiz/hugo-theme-monochrome#18]
Hugo automatically generates IDs for header elements [via the functionality in the BlackFriday markdown parser](https://github.com/russross/blackfriday#sanitized-anchor-names=), and it is a somewhat common feature to create `<a>` elements next to these headers (or appearing on hover) which link to these IDs for ease of copying links to specific headings on a blog post. Monochrome currently does not have any such link present, on hover or otherwise. Could this be added?

**Comment by kaiiiz** [comment]
I think this feature can be done by regular expression replacement for the `.Content` rendered from hugo. I'll add this to TODO, thanks for the suggestion.

**Comment by kaiiiz** [comment]
Implemented in v3.1.0
