### ISSUE TITLE
Support all Feather icons, not just a few

### ISSUE THREAD

**Issue by Nightfirecat** [kaiiiz/hugo-theme-monochrome#19]
Rather than only providing a limited set of the Feather sprites, the entire spritesheet could be included [via client-side JS](https://github.com/feathericons/feather#client-side-javascript=), or the full set could be [installed with Node](https://github.com/feathericons/feather#node=) or [included from the sprite sheet](https://github.com/feathericons/feather#svg-sprite=). This would give users better access to sprites than just a small small set of them.

**Comment by kaiiiz** [comment]
Thanks for the suggestion. I think adding sprite sheet to the asset bundle is a better solution than using node or client-side JS. By extending the `icon` shortcode, users can access a full set of feathericons. Meanwhile, the other theme components can also benefit from these changes.

**Comment by Ran-n** [comment]
you should support more icons than just feathers tbh they are very limited

**Comment by kaiiiz** [comment]
Implemented in v2.0.0.
