### ISSUE TITLE
existing setup instructions do not render site pages when running `hugo server`

### ISSUE THREAD

**Issue by hieu6** [kaiiiz/hugo-theme-monochrome#2]
I followed the [setup instructions](https://kaiiiz.github.io/hugo-theme-monochrome/setup/) exactly, but when I run `hugo server` at root, none of the html renders. I deleted the examplesite and tried again but that didn't help. not sure if it made things worse! 

I am not used to running npm when starting a site, so I'll try again without. 

The repo is here: https://github.com/hieu6/curioushieu

a note to document for other noobs like me that the instructions as is don't quite work yet!

thank you for any advice you could offer.

hieu

**Comment by hieu6** [comment]
turns out my npm version was not updated 😅

also, there was a small hiccup: `home.html` in `theme/layouts` was calling the partial`tag-cloud.html`. the partial itself was actually named `terms-cloud.html` so renaming it as such in `home.html` fixed it.

it's working beautifully. 🥰

**Comment by kaiiiz** [comment]
I'm glad you enjoy the theme, and thanks for the bug report. I'll fix it in the next release soon.

**Comment by kaiiiz** [comment]
Merged #4
