### ISSUE TITLE
Change the title of a bookcase with a bookcase layout

### ISSUE THREAD

**Issue by Ran-n** [kaiiiz/hugo-theme-monochrome#20]
When you have a element that is part of a bookcase layout that has a bookcase layout in itself its not possible to change the title by using # or title tag. It automatically puts the page title as its title and it can not be changed. 

It would be nice if it could be changed.

**Comment by Ran-n** [comment]
Also, it would be great if you could have a variable that allows you put a custom name on the page on the bookcase layout (https://kaiiiz.github.io/hugo-theme-monochrome/layouts/bookcase/demo/) so that it doesnt use the file name or page title.

And the power to put the bookcase layout in between text. Right now, if you write anything in the page the layout is show at the bottom. It would be nice to have an option to be able to pinpoint the location of the layout within the webpage.

**Comment by kaiiiz** [comment]
> When you have a element that is part of a bookcase layout that has a bookcase layout in itself its not possible to change the title by using # or title tag. It automatically puts the page title as its title and it can not be changed.
> 
> It would be nice if it could be changed.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/30596812/171568382-88aa6f7b-820e-499b-95fa-c0154428bcdb.png">

It's confusing to use the term "Title" as there are two title-related components on the same page. I'm not sure your title is the blue part or the red part in the above figure.

> Also, it would be great if you could have a variable that allows you put a custom name on the page on the bookcase layout ([kaiiiz.github.io/hugo-theme-monochrome/layouts/bookcase/demo](https://kaiiiz.github.io/hugo-theme-monochrome/layouts/bookcase/demo/)) so that it doesnt use the file name or page title.

I open a separate issue #32 for this feature.

> And the power to put the bookcase layout in between text. Right now, if you write anything in the page the layout is show at the bottom. It would be nice to have an option to be able to pinpoint the location of the layout within the webpage.

This is way more complex than the bookcase implementation right now. I think you need to build such a page with the Blank Layout and a bookcase-like shortcode (currently not implemented yet). This brings you more flexibility and does not clutter the layout options with lots of rarely used options.

**Comment by kaiiiz** [comment]
Implemented in v2.0.0.
