### ISSUE TITLE
Modes color/shade

### ISSUE THREAD

**Issue by Ran-n** [kaiiiz/hugo-theme-monochrome#23]
I think it would great to allow the control of the light/dark mode colors.
The night one would be more of a shade since it has to be dark but the light one allows the programmer to use other colors than white.
Also, with this the change of the text color and font would be great.

I image it in the global config file like this:
background_color_light: hex_value
background_color_dark: hex_value

background_image_light: path
background_image_dark: path

text_color_light: hex_value
text_color_dark: hex_value

text_font_light: path
text_font_dark: path

By default (if no option added) use the current ones.

**Comment by kaiiiz** [comment]
This is the feature that I don't want to include as this brings challenges to maintaining these parameters while more features are implemented in the future.

A better solution to bring more flexibility of style control to the end-user is to add a `custom_css` option and bundle it in `head.html`. User can create a custom CSS to override the style variable defined in `html[data-theme="light"]` for the light theme and `html[data-theme="dark"]` for the dark theme. (see https://github.com/kaiiiz/hugo-theme-monochrome/blob/main/assets/scss/color.scss)

**Comment by kaiiiz** [comment]
I've created a separate issue for this improvement with a different implementation, so this issue should be closed.
