### ISSUE TITLE
terms-cloud ordering

### ISSUE THREAD

**Issue by Ran-n** [kaiiiz/hugo-theme-monochrome#26]
When i create a taxonomy with contents like 1.8 1.9 1.10 etc the expected behaviour when using a terms-cloud would be to have them ordered like that. Instead, it shows them like 1.10 1.8 1.9

**Comment by Ran-n** [comment]
Ive checked the terms-cloud.html and you seem to use calculated $weight variable. Would it be possible to add a option to set each vale weight individually?

**Comment by kaiiiz** [comment]
> When i create a taxonomy with contents like 1.8 1.9 1.10 etc the expected behaviour when using a terms-cloud would be to have them ordered like that. Instead, it shows them like 1.10 1.8 1.9

This is expected behavior since `1.8`, `1.9`, and `1.10` are strings. Sorting string is sequentially compared character by character. A compromise to this problem is that you should rename `1.8` to `1.08`.

> Ive checked the terms-cloud.html and you seem to use calculated $weight variable. Would it be possible to add a option to set each vale weight individually?

`$weight` is only used for calculating `$fontSize`, it does nothing about sorting.
