### ISSUE TITLE
Hide a section in a bookcase layout

### ISSUE THREAD

**Issue by Ran-n** [kaiiiz/hugo-theme-monochrome#27]
As it is right now, when you define a folder as a bookcase layout you will have all sections or all pages listed (changable in the options). But when you want to list all sections but one, you really cant control that; i would be nice if it where possible.

I image it with a single option (like weight for example): hidden: 0/1 (0 for no 1 for yes)

**Comment by kaiiiz** [comment]
Yes, this is a nice-to-have feature and it's simple to implement.

**Comment by kaiiiz** [comment]
Implemented in v2.0.0.
