### ISSUE TITLE
Improvement: Bookcase Layout

### ISSUE THREAD

**Issue by Ran-n** [kaiiiz/hugo-theme-monochrome#28]
It would be nice if there was an option to make it so the bookcase layout would read from a specific directory other than the one the _index file is in. A similar behaviour as the balloon or gallery layouts. 
I image it like:

\-\-\-
bookcase_resources: 'path'
\-\-\-

If no resource is given keep the current behaviour of using the current folder of the _index location

**Comment by kaiiiz** [comment]
The purpose of the Bookcase Layout is to create another view of the List Layout, so I expect most of the use cases of the Bookcase Layout is the same as the List Layout.

I think what you try to do is to use a bookcase-like shortcode with the Blank Layout as I mentioned in [#20](https://github.com/kaiiiz/hugo-theme-monochrome/issues/20#issuecomment-1144504127). This shortcode will take a parameter like your proposed `bookcase_resources` and render a bookcase list on the page, which brings more flexibility to the advanced user and doesn't go against the design principle of the Bookcase Layout.

**Comment by kaiiiz** [comment]
I opened a separate issue #34 for the implementation detail of the bookcase-like shortcode, so I'll close this issue.
