### ISSUE TITLE
Javascript-free version of this theme

### ISSUE THREAD

**Issue by pawelngei** [kaiiiz/hugo-theme-monochrome#30]
First and foremost, thank you for your work. 

I'm considering modifying your theme to be fully JavaScript-free (or rather: allowing you to turn off `header.js`), making the light / dark mode and mobile sidebar CSS-only.

Would you welcome such a PR, or should I just fork and use it in my own version?

**Comment by kaiiiz** [comment]
PR of these improvements is absolutely welcome! I'm looking forward to such changes. Feel free to open an issue if there is anything I can help with.
