### ISSUE TITLE
Center images

### ISSUE THREAD

**Issue by krnb** [kaiiiz/hugo-theme-monochrome#35]
Hi, I'm not an advanced user so I'm unable to work around with custom css but I feel that if we add `display: flex` to base.scss then not only would images be centered but upon my testing with your blog and example site it also does not adversely affect it.

I'd like to continue using your theme as a sub-module and if there is another way to center the images then please let me know. Thanks.

**Comment by kaiiiz** [comment]
Implemented in v2.0.0.
