### ISSUE TITLE
Google Analytics v4

### ISSUE THREAD

**Issue by benoitparis** [kaiiiz/hugo-theme-monochrome#37]
GA v4 needs another default template from Hugo:

in https://github.com/kaiiiz/hugo-theme-monochrome/blob/55458417cbbe9caeee6fb3b7ea2fcbecc60fda70/layouts/partials/head.html

replace `google_analytics_async.html` by `google_analytics.html` to activate GA v4.

(Per https://gohugo.io/templates/internal/#use-the-google-analytics-template)

I don't know if you want to parameterize it @kaiiiz; but anyway here it is if someone else needs GA v4

**Comment by kaiiiz** [comment]
Implemented in v2.0.0.
