### ISSUE TITLE
How to set dark mode as the default?

### ISSUE THREAD

**Issue by penyuan** [kaiiiz/hugo-theme-monochrome#40]
This theme has support for dark and light mode, but **is there a way to make dark mode the default?**

Thank you to @kaiiiz for making this theme!

**Comment by zhtsu** [comment]
I did it like this:

- Swap the value of data-theme in line 22 and 40 of file 'assets/scss/color.scss'
- Swap the contents of file 'moon.html' and 'sun.html' in the 'layouts/partials/svg'

It's hack but working PERFECT!!! XD

**Comment by kaiiiz** [comment]
Implemented in v2.0.0.
