### ISSUE TITLE
balloon配置出现问题

### ISSUE THREAD

**Issue by fcjz** [kaiiiz/hugo-theme-monochrome#41]
感谢你开发出这个好用的主题，它十分美观，不过我在配置主页（就像官网那样）balloon布局时似乎出现了些小问题。

是这样的：

我在content文件夹中新建了一个名为“about”的文件夹，又新建了“_index.md”的主页，我在主页页首成功配置了balloon_img_src，但在资源配置上除了问题，按理来说我的about页面链接应该是"https://……/about"，但我无论输入"/about"还是"./about"都没有成功配置。

“ There is no page under /about. You need to specify "balloon_resources" correctly in front-matter and check the existence of posts under this folder. ”

不知这是怎么回事呢？希望可以得到解答，感谢每一个解答这个问题的开发者。

（我的文件夹是直接在content右键新建的，不知是否和这个有关，但我使用命令往这个文件夹中添加文章并没有问题，而且，怎样通过命令新建文件夹呢？）

**Comment by kaiiiz** [comment]
請提供一個可以 reproduce 這個問題的環境，謝謝

**Comment by kaiiiz** [comment]
Closed due to inactivity.
