### ISSUE TITLE
Permalink produces a " character for postcard layout in live build.

### ISSUE THREAD

**Issue by shervinsahba** [kaiiiz/hugo-theme-monochrome#42]
Hi kaiiiz. First of all, thank you for the lovely theme!

On my live build, the postcard links are broken. It appears that [the call to {{ .Permalink }} here](https://github.com/kaiiiz/hugo-theme-monochrome/blob/55458417cbbe9caeee6fb3b7ea2fcbecc60fda70/layouts/partials/postcard/layout.html) causes a quotation character to be inserted in the URL for some reason. 

Here is an example from my site. Clicking the postcard fails on Firefox and breaks on Chrome. I printed the output of `{{ .Permalink }}` and saw this
![image](https://user-images.githubusercontent.com/25020522/226751123-644359c0-99a2-4ad8-affd-bc1dc1a16480.png)

The actual page does exist if you retype the URL without the quotation mark. The quote seems to only appear for postcards from what I've seen so far.

Did I mess something up, or is this a bug?

**Comment by shervinsahba** [comment]
I made [this hacky fix](https://github.com/shervinsahba/hugo-sherv/blob/191345182737eb94fba173068140136d7d135ef3/layouts/partials/postcard/layout.html#L6) to the problematic line in layout.html. I don't know what the underlying issue was, but this is working for now, I think.

Changed

`<a href="{{ .Permalink }}">`

to

`<a href="{{ .Permalink | replaceRE "\"" ""}}">`

**Comment by kaiiiz** [comment]
Can you provide your `BaseURL` setting? I think this is caused by a inappropriate `"` suffix in your BaseURL setting.

**Comment by kaiiiz** [comment]
Closed due to inactivity.
