### ISSUE TITLE
TOC Depth

### ISSUE THREAD

**Issue by matbog** [kaiiiz/hugo-theme-monochrome#45]
Hi, I was wondering if the TOC depth is a parameter that could be exposed ?
I tried looking through the theme config files and partials, but couldn't figure a way to enable H4 and H5 headings... 
Any thoughts on how this could be achieved? 

(and thanks for the nice an clean theme!)

**Comment by kaiiiz** [comment]
This can be configured through the `markup` settings. Refer to [hugo's doc](https://gohugo.io/getting-started/configuration-markup/#table-of-contents).
