### ISSUE TITLE
How to not show recent post on home page?

### ISSUE THREAD

**Issue by adibtatriantama** [kaiiiz/hugo-theme-monochrome#48]
When I create content in `/post` or `/blog`, the homepage will automatically display the list of posts.

is there a way to set the homepage not to show the recent post?

thank you for creating this theme.

**Comment by adibtatriantama** [comment]
I solved this by overriding the `layouts/home.html`
```
{{ define "content" }}

{{ if .Content }}
    <div class="content-margin">
        {{- partial "content.html" (dict "ctx" . "content" .Content) -}}
    </div>
{{ end }}

{{ partial "postcard/layout.html" (dict "pages" .Site.RegularPages "ctx" .) }}

{{ end }}
```
and removing this line
```
{{ partial "postcard/layout.html" (dict "pages" .Site.RegularPages "ctx" .) }}
```

**Comment by kaiiiz** [comment]
I think what you want to do is to use [Blank layout](https://kaiiiz.github.io/hugo-theme-monochrome/layouts/blank/) in home page, which is less hacky than modifying the theme code.
