### ISSUE TITLE
Using i18n translations in partials/nav.html

### ISSUE THREAD

**Issue by JulianSchutsch** [kaiiiz/hugo-theme-monochrome#49]
Hi,

The issue was, that the translation entries in i18n for some custom menu entries were ignored. Checking nav.html i applied the suggestions for menu: https://gohugo.io/templates/menu-templates/#example to nav.html:

.Name  -----> or (T .Identifier) .Name | safeHTML

which resulted in the i18n entries being properly used. Would this code break in some cases i might not considered?

This also affects: sidebar.html, nested-desktop.html, nested-mobile.html.

**Comment by kaiiiz** [comment]
Fixed in v3.0.0.
