### ISSUE TITLE
Error when building sites

### ISSUE THREAD

**Issue by Saladoc** [kaiiiz/hugo-theme-monochrome#5]
Log Output:

```
Start building sites … 
hugo v0.89.4+extended linux/amd64 BuildDate=unknown
Error: Error building site: JSBUILD: failed to transform "js/zooming.js" (application/javascript): Could not resolve "zooming" (mark it as external to exclude it from the bundle)
Built in 3028 ms
```

Steps I took: 
 - Added Theme as submodule according to documentation
 - Ran `npm install` in theme directory
 - Ran `hugo server`

**Comment by kaiiiz** [comment]
Hi, you should run `npm install` in the project directory instead of the theme directory.
