### ISSUE TITLE
Single Page Demo for balloon layout not working

### ISSUE THREAD

**Issue by hrishikeshh** [kaiiiz/hugo-theme-monochrome#50]
On the demonstration site [here](https://kaiiiz.github.io/hugo-theme-monochrome/layouts/balloon/demo/), the single-page view for the balloon layout is not working (click on it). 

Moreover, when I try to recreate a balloon layout based on the structure given in the [documentation](https://kaiiiz.github.io/hugo-theme-monochrome/layouts/balloon/docs/) and placing the necessary files in a sample '/about' folder, it gives this error while rendering. [Source](https://hrishikeshh.github.io/about/)

![image](https://github.com/kaiiiz/hugo-theme-monochrome/assets/12010904/f7624153-d7f4-4804-a1ad-bd5e5b43236f)

Help will be appreciated. Thanks

**Comment by kaiiiz** [comment]
I've checked your website and found some misconfigured configs.

1. `balloon_resources` should be `/about` instead of `/content/about`
2. `content/about/_index.md` should be renamed to `content/about/index.md` (this is the bug that I'll resolve later. It should work fine for both `_index.md` and `index.md` after the fix)

**Comment by hrishikeshh** [comment]
Thanks for the prompt reply @kaiiiz 

> 1. `balloon_resources` should be `/about` instead of `/content/about`

I was trying out for various paths (absolute and relative). 

> 2. `content/about/_index.md` should be renamed to `content/about/index.md` (this is the bug that I'll resolve later. It should work fine for both `_index.md` and `index.md` after the fix)

Renaming the ```_index.md``` as ```index.md``` solved this issue for now.

**Comment by hrishikeshh** [comment]
Hey @kaiiiz, 
Thanks for this beautiful theme. 

I have few observation, 
1. Whenever single page `index.md` is used inside the nested content to provide for individual pages for each nested folders, then it is not being rendered by Hugo. 
2. If `_index.md` is used then first component of `_index.md` can be user provided but at the end of the file, all the other markdown files in the current folder are rendered on the current file as hyperlinks. 

Can you please fix this bug ? Thanks :)

**Comment by kaiiiz** [comment]
Fixed in v3.0.0.
