### ISSUE TITLE
Math typesetting creates white pixels on top and bottom left of page

### ISSUE THREAD

**Issue by ericlovesmath** [kaiiiz/hugo-theme-monochrome#56]
This error is visible even in the demo: https://kaiiiz.github.io/hugo-theme-monochrome/posts/math-typesetting/

![Screenshot 2024-08-27 at 5 26 43 PM](https://github.com/user-attachments/assets/b5be59ca-ad4a-4a06-9c39-652fa4550eaa)
![Screenshot 2024-08-27 at 5 26 47 PM](https://github.com/user-attachments/assets/3fc78b9f-2c8a-428d-aaa1-89baf123b434)

**Comment by kaiiiz** [comment]
Fixed in v4.0.0.
