### ISSUE TITLE
Maximum of 10 post titles on home page 

### ISSUE THREAD

**Issue by jeregg** [kaiiiz/hugo-theme-monochrome#8]
Under the list view, it looks like the home page can only show the recent 10 post titles. 

Does anyone know how can I adjust to show all post titles? Or display pages to navigate through 10 post titles each?

Thanks

**Comment by kaiiiz** [comment]
Hi,

The current implementation of the default homepage still lacks customizability as it is not used on my website.

I suggest the workaround for now:

To show all post titles, you need to change the following line from `(first 10 .Site.RegularPages)` to `.Site.RegularPages`

https://github.com/kaiiiz/hugo-theme-monochrome/blob/v0.9.2/layouts/home.html#L19

Display pages to navigate through 10 post titles each?

The pagination feature has not been designed yet.

If time permits, support for pagination feature and a redesign of the homepage will be in the near future.

**Comment by jeregg** [comment]
Perfect. That works.

Thank you for your reply. And I had so much fun playing with the Monochrome theme.
