### ISSUE TITLE
terms-cloud naming issue

### ISSUE THREAD

**Issue by Ran-n** [kaiiiz/hugo-theme-monochrome#9]
When I define a terms with a nome other than tags the terms-cloud doesnt render.

**Comment by kaiiiz** [comment]
Hugo supports `tag` and `category` terms by default. If you want to add your custom terms, please first check your hugo project's `config.yaml` has following settings:

```
taxonomies:
  category: categories
  tag: tags
  singular key: plural value
```

See https://gohugo.io/content-management/taxonomies for more details.

**Comment by Ran-n** [comment]
Tysm that was the issue.
Also, great of you guys to add it in since it was kinda missleading.
